### PR TITLE
Feat: Avatar added

### PR DESCRIPTION
**Pull request by KanekarSnehal**
Animation

### CODE REVIEW

**Comment by AmishMishra11** [comment]
In avatar.css in the third line, you don't need flex-direction: row and its default so that an extra line of code you don't need, rest all looks good

**Comment by ashishnnnnn** [comment]
Code seems fine!! :+1:

**Comment by KanekarSnehal** [comment]
> In avatar.css in the third line, you don't need flex-direction: row and its default so that an extra line of code you don't need, rest all looks good

Oh yes, I will make the changes, thanks for your feedback.

**Comment by Prabhav-Sharma** [comment]
In the avatar with initials, the size of the characters remain the same which doesn't produce a good visual

**Pull request merged**
